# -*- coding: utf-8 -*-
"""Underwater_Dataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YpOIyZCM_s38JhTsu6ysx99sK2_IEWOJ
"""

# Step 1: Install Required Libraries
!pip install kaggle torch torchvision matplotlib seaborn

# Step 2: Set Up Kaggle API and Download Dataset
from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d akshatsng/underwater-dataset-for-8-classes-with-label
!unzip underwater-dataset-for-8-classes-with-label.zip -d underwater_dataset

# Step 3: Import Necessary Libraries
import torch
import torchvision
from torchvision.models.detection import FasterRCNN
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torchvision.transforms import functional as F
from torchvision import transforms
from torch.utils.data import DataLoader, Dataset
import os
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import json
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

# Step 4: Define the Dataset Class with Augmentation Support
class UnderwaterDataset(Dataset):
    def __init__(self, root_dir, annotations_dir, class_map, transform=None, augment=False):
        """
        Args:
        - root_dir (str): Path to the directory with images.
        - annotations_dir (str): Path to the directory with .txt annotation files.
        - class_map (dict): A dictionary mapping class names to numeric labels.
        - transform (callable, optional): Transform to be applied to images.
        - augment (bool): Whether to apply data augmentation.
        """
        self.root_dir = root_dir
        self.annotations_dir = annotations_dir
        self.class_map = class_map
        self.transform = transform
        self.augment = augment
        self.image_files = sorted([f for f in os.listdir(root_dir) if f.endswith('.jpg')])
        self.annotation_files = sorted([f for f in os.listdir(annotations_dir) if f.endswith('.txt')])

    def __len__(self):
        return len(self.image_files)

    def __getitem__(self, idx):
        # Load image
        img_path = os.path.join(self.root_dir, self.image_files[idx])
        image = Image.open(img_path).convert("RGB")

        # Load corresponding annotation
        ann_path = os.path.join(self.annotations_dir, self.annotation_files[idx])
        boxes = []
        labels = []
        with open(ann_path, 'r') as file:
            for line in file.readlines():
                values = line.strip().split()
                x_coords = list(map(float, values[:8:2]))
                y_coords = list(map(float, values[1:8:2]))
                class_name = values[8]
                # Convert quadrilateral to bounding box (xmin, ymin, xmax, ymax)
                xmin, ymin, xmax, ymax = min(x_coords), min(y_coords), max(x_coords), max(y_coords)
                boxes.append([xmin, ymin, xmax, ymax])
                labels.append(self.class_map[class_name])  # Convert class name to numeric label

        boxes = torch.tensor(boxes, dtype=torch.float32)
        labels = torch.tensor(labels, dtype=torch.int64)

        target = {'boxes': boxes, 'labels': labels}

        # Apply data augmentation if specified
        if self.augment:
            if random.random() > 0.5:
                image = F.hflip(image)
                boxes[:, [0, 2]] = image.width - boxes[:, [2, 0]]  # Adjust bounding boxes for horizontal flip
            if random.random() > 0.5:
                angle = random.choice([90, 180, 270])
                image = F.rotate(image, angle)
                if angle == 90:
                    boxes[:, [1, 3]] = image.height - boxes[:, [3, 1]]
                    boxes[:, [0, 2]] = boxes[:, [1, 3]]
                elif angle == 180:
                    boxes[:, [0, 2]] = image.width - boxes[:, [2, 0]]
                    boxes[:, [1, 3]] = image.height - boxes[:, [3, 1]]
                elif angle == 270:
                    boxes[:, [1, 3]] = boxes[:, [0, 2]]
                    boxes[:, [0, 2]] = image.width - boxes[:, [2, 0]]

        if self.transform:
            image = self.transform(image)

        return image, target

# Step 5: Define Data Transformations
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

# Step 6: Define Class Mapping
class_map = {
    "Fish": 1,
    "Crab": 2,
    "Human": 3,
    "Trash": 4,
    "Jelly-fish": 5,
    "Coral-Reef": 6,
    "Fish-Group": 7
}

# Step 7: Load Datasets
train_dataset = UnderwaterDataset(
    root_dir="/content/underwater_dataset/train/images",
    annotations_dir="/content/underwater_dataset/train/labelTxt",
    class_map=class_map,
    transform=transform,
    augment=True

)

val_dataset = UnderwaterDataset(
    root_dir="/content/underwater_dataset/valid/images",
    annotations_dir="/content/underwater_dataset/valid/labelTxt",
    class_map=class_map,
    transform=transform,
)

train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True, collate_fn=lambda x: tuple(zip(*x)))
val_loader = DataLoader(val_dataset, batch_size=4, shuffle=False, collate_fn=lambda x: tuple(zip(*x)))

# Step 8: Define the Model
def get_model(num_classes):
    model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
    in_features = model.roi_heads.box_predictor.cls_score.in_features
    model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)
    return model

model = get_model(num_classes=8)  # 8 classes + 1 background
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
model.to(device)

# Step 9: Define Optimizer and Scheduler
optimizer = torch.optim.SGD(model.parameters(), lr=0.005, momentum=0.9, weight_decay=0.0005)
lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=3, gamma=0.1)

test_dataset = UnderwaterDataset(
    root_dir="/content/underwater_dataset/test/images",
    annotations_dir="/content/underwater_dataset/test/labelTxt",
    class_map=class_map,
    transform=transform,
)

test_loader = DataLoader(test_dataset, batch_size=4, shuffle=False, collate_fn=lambda x: tuple(zip(*x)))




# Training Loop
num_epochs = 30  # Set the number of epochs
train_losses = []  # List to store training loss per epoch
train_accuracies = []  # List to store training accuracy per epoch
val_accuracies = []  # List to store validation accuracy per epoch
val_losses = []  # List to store validation loss per epoch
test_losses = []  # List to store test loss per epoch

for epoch in range(num_epochs):
    model.train()  # Set model to training mode
    train_loss = 0  # Initialize cumulative training loss for the epoch
    correct = 0
    total = 0
    for images, targets in train_loader:
        # Move images and targets to the device (GPU/CPU)
        images = [img.to(device) for img in images]
        targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

        # Forward pass: compute the loss dictionary
        loss_dict = model(images, targets)

        # Sum up the losses (e.g., classification, bounding box regression, etc.)
        losses = sum(loss_dict.values())

        # Backward pass and optimizer step
        optimizer.zero_grad()
        losses.backward()
        optimizer.step()

        # Add the batch loss to the cumulative loss
        train_loss += losses.item()

        # Get model outputs
        model.eval()  # Temporarily set model to evaluation mode
        with torch.no_grad():
          outputs = model(images)
          for i, output in enumerate(outputs):
              if 'labels' in output:  # Check if predictions are non-empty
                  labels = targets[i]['labels'].cpu().numpy()
                  preds = output['labels'].cpu().numpy()[:len(labels)]
                  while(len(labels) > len(preds)):
                    preds = np.append(preds, 0)
                  correct += (preds == labels).sum()
                  total += len(labels)
        model.train()

    # Compute average training loss for the epoch
    train_accuracy = correct / total if total > 0 else 0
    train_accuracies.append(train_accuracy)
    avg_train_loss = train_loss / len(train_loader)
    train_losses.append(avg_train_loss)

    print(f"Epoch [{epoch + 1}/{num_epochs}], Train Loss: {avg_train_loss:.4f}, Train Accuracy: {train_accuracy:.4f}")

    model.eval()  # Set model to evaluation mode
    val_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():  # Disable gradient calculation for evaluation
        for images, targets in val_loader:
            # Move images and targets to the device (GPU/CPU)
            images = [img.to(device) for img in images]
            targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

            model.train()
            # Forward pass: compute the loss dictionary
            loss_dict = model(images, targets)

            # Sum up the losses (e.g., classification, bounding box regression, etc.)
            losses = sum(loss_dict.values())


            # Add the batch loss to the cumulative loss
            val_loss += losses.item()

            model.eval()


            # Get model outputs
            outputs = model(images)
            for i, output in enumerate(outputs):
                if 'labels' in output:  # Check if predictions are non-empty
                    labels = targets[i]['labels'].cpu().numpy()
                    preds = output['labels'].cpu().numpy()[:len(labels)]
                    while(len(labels) > len(preds)):
                      preds = np.append(preds, 0)
                    correct += (preds == labels).sum()
                    total += len(labels)

    # Compute average validation loss and accuracy
    val_accuracy = correct / total if total > 0 else 0
    val_accuracies.append(val_accuracy)
    avg_val_loss = val_loss / len(val_loader)
    val_losses.append(avg_val_loss)

    print(f"Epoch [{epoch + 1}/{num_epochs}], Validation Loss: {avg_val_loss:.4f}, Val Accuracy: {val_accuracy:.4f}")




    # Testing Loop
    test_loss = 0
    correct = 0
    total = 0

    model.eval()  # Set model to evaluation mode
    with torch.no_grad():
        for images, targets in test_loader:
            images = [img.to(device) for img in images]
            targets = [{k: v.to(device) for k, v in t.items()} for t in targets]


            model.train()
            # Forward pass: compute the loss dictionary
            loss_dict = model(images, targets)

            # Sum up the losses (e.g., classification, bounding box regression, etc.)
            losses = sum(loss_dict.values())


            # Add the batch loss to the cumulative loss
            test_loss += losses.item()

            model.eval()

            # Get predictions and calculate accuracy
            outputs = model(images)
            for i, output in enumerate(outputs):
                if 'labels' in output:  # Check if predictions are non-empty
                    labels = targets[i]['labels'].cpu().numpy()
                    preds = output['labels'].cpu().numpy()[:len(labels)]
                    while(len(labels) > len(preds)):
                      preds = np.append(preds, 0)
                    correct += (preds == labels).sum()
                    total += len(labels)

    # Compute average test loss and accuracy
    test_accuracy = correct / total if total > 0 else 0
    avg_test_loss = test_loss / len(test_loader)
    test_losses.append(avg_test_loss)

    print(f"Epoch [{epoch + 1}/{num_epochs}], Test Loss: {avg_test_loss:.4f}, Test Accuracy: {test_accuracy:.4f}")

import matplotlib.pyplot as plt

print(train_accuracies)
print(val_accuracies)

# Plot validation accuracy
plt.figure(figsize=(10, 6))
plt.plot(val_accuracies, label='Validation Accuracy')
plt.plot(train_accuracies, label='Train Accuracy')
# plt.axhline(y=test_accuracy, color='r', linestyle='--', label='Test Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Validation and Test Accuracy')
plt.legend()
plt.show()

# Plot validation accuracy
plt.figure(figsize=(10, 6))
plt.plot(val_losses, label='Validation Loss')
plt.plot(train_losses, label='Train Loss')
# plt.axhline(y=test_accuracy, color='r', linestyle='--', label='Test Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Validation and Test Accuracy')
plt.legend()
plt.show()

# Step 11: Evaluation
model.eval()
all_preds = []
all_labels = []
with torch.no_grad():
    for images, targets in val_loader:
        images = [img.to(device) for img in images]
        outputs = model(images)
        # print(targets)
        for i, output in enumerate(outputs):
            labels = targets[i]['labels'].cpu().numpy()
            preds = output['labels'].cpu().numpy()[:len(labels)]
            lst = output['scores'].cpu().numpy()
            # if not all(lst[i] >= lst[i + 1] for i in range(len(lst) - 1)):
            #   print("not sorted")
            while(len(labels) > len(preds)):
                preds = np.append(preds, 0)
            # print("Predicted")
            # print(output['boxes'].cpu().numpy()[:len(labels)], "   ", preds)
            # print(output['scores'].cpu().numpy()[:len(labels)], "   ", preds)
            all_preds.extend(preds)
            # print("Actual")
            # print(targets[i]['boxes'].cpu().numpy(), "   ", labels)
            all_labels.extend(labels)
    outputs = model(images)
    print(outputs[0])

print(len(all_preds))
print(len(all_labels))

# Step 12: Classification Report
print("Classification Report:")
print(classification_report(all_labels, all_preds))

# Step 13: Confusion Matrix
conf_matrix = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(10, 8))
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.show()